server:
  port: 8080
spring:
  redis:
    host: 39.106.49.241
    port: 6380
    password: 1234567788
  profiles:
    include: jodconverter
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

jodconverter:
  local:
    enabled: false
    max-tasks-per-process: 10
    port-numbers: 8100,8101,8102,8103
    taskExecutionTimeout: 200000
    officeHome: C:\Program Files\LibreOffice
  online:
    enabled: true
    url: http://81.70.239.72:9980/
    taskExecutionTimeout: 200000
    taskQueueTimeout: 200000
    ssl:
      enabled: false
