server:
  port: 8080
spring:
  #  redis:
  #    host: 39.106.49.241
  #    port: 6380
  #    password: 1234567788
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: guest
    username: guest
    virtual-host: /
    listener:
      type: simple
      simple:
        acknowledge-mode: manual
        # 没此获取多少条消息
        prefetch: 10
        concurrency: 1
#        max-concurrency: 10

  sleuth:
    sampler:
      probability: 1 #百分之多少的sleuth信息需要输出到zipkin（1代表全部100%）
  zipkin:
    enabled: false
    base-url: http://127.0.0.1:9411/  #指定zipkin的地址


jodconverter:
  local:
    enabled: false
    max-tasks-per-process: 10
    port-numbers: 8100
    # 一个任务执行的时间
    taskExecutionTimeout: 200000
    # 一个任务在队列中等待的时间
    taskQueueTimeout: 200000
    officeHome: C:\Program Files\LibreOffice
  online:
    enabled: false
    url: http://81.70.239.72:9980/
    taskExecutionTimeout: 200000
    taskQueueTimeout: 200000
    ssl:
      enabled: false
