package com.zhy.other.groovy.controller;

import com.zhy.other.groovy.loader.GroovyLoader;
import com.zhy.other.groovy.loader.ILoader;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.annotation.Resource;

/**
 * GroovyController
 *
 * @author zhouhongyin
 * @since 2023/5/20 12:37
 */
@RequestMapping("groovy")
@RestController
public class GroovyController {
    @Resource
    private GroovyLoader groovyLoader;

    @GetMapping
    public String test() throws Exception {

        String scriptBase64 = "cGFja2FnZSBjb20uemh5Lm90aGVyLmdyb292eS5sb2FkZXI7CgppbXBvcnQgY24uaHV0b29sLmNvcmUuaW8uSW9VdGlsOwppbXBvcnQgb3JnLnNwcmluZ2ZyYW1ld29yay5iZWFucy5mYWN0b3J5LmFubm90YXRpb24uQXV0b3dpcmVkOwppbXBvcnQgb3JnLnNwcmluZ2ZyYW1ld29yay5odHRwLkh0dHBIZWFkZXJzOwppbXBvcnQgb3JnLnNwcmluZ2ZyYW1ld29yay5zdGVyZW90eXBlLkNvbXBvbmVudDsKaW1wb3J0IG9yZy5zcHJpbmdmcmFtZXdvcmsud2ViLmNvbnRleHQucmVxdWVzdC5SZXF1ZXN0Q29udGV4dEhvbGRlcjsKaW1wb3J0IG9yZy5zcHJpbmdmcmFtZXdvcmsud2ViLmNvbnRleHQucmVxdWVzdC5TZXJ2bGV0UmVxdWVzdEF0dHJpYnV0ZXM7CgppbXBvcnQgamF2YXguc2VydmxldC5TZXJ2bGV0T3V0cHV0U3RyZWFtOwppbXBvcnQgamF2YXguc2VydmxldC5odHRwLkh0dHBTZXJ2bGV0UmVxdWVzdDsKaW1wb3J0IGphdmF4LnNlcnZsZXQuaHR0cC5IdHRwU2VydmxldFJlc3BvbnNlOwppbXBvcnQgamF2YS5pby5GaWxlSW5wdXRTdHJlYW07CmltcG9ydCBqYXZhLmlvLklPRXhjZXB0aW9uOwoKLyoqCiAqIOiOt+WPluWKoOi9veexu+WQjeensAogKgogKiBAYXV0aG9yIHpob3Vob25neWluCiAqIEBzaW5jZSAyMDIzLzUvMjAgMTE6NTQKICovCkBDb21wb25lbnQKcHVibGljIGNsYXNzIE15TG9hZGVyIGltcGxlbWVudHMgSUxvYWRlciB7CgogICAgQEF1dG93aXJlZAogICAgcHJpdmF0ZSBBdXRvd2lyZWRCZWFuIGF1dG93aXJlZEJlYW47CgogICAgcHVibGljIFN0cmluZyBnZXRMb2FkZXJOYW1lKCkgdGhyb3dzIEV4Y2VwdGlvbiB7CiAgICAgICAgYXV0b3dpcmVkQmVhbi5wcmludCgpOwoKICAgICAgICBIdHRwU2VydmxldFJlc3BvbnNlIHJlc3BvbnNlID0gZ2V0UmVzcG9uc2UoKTsKICAgICAgICBTZXJ2bGV0T3V0cHV0U3RyZWFtIG91dHB1dFN0cmVhbSA9IHJlc3BvbnNlLmdldE91dHB1dFN0cmVhbSgpOwoKICAgICAgICByZXNwb25zZS5zZXRIZWFkZXIoSHR0cEhlYWRlcnMuQ09OVEVOVF9ESVNQT1NJVElPTiwgImlubGluZTtmaWxlbmFtZT1hLmRvY3giKTsKICAgICAgICByZXNwb25zZS5zZXRIZWFkZXIoSHR0cEhlYWRlcnMuQ09OVEVOVF9UWVBFLCAiYXBwbGljYXRpb24vdm5kLm9wZW54bWxmb3JtYXRzLW9mZmljZWRvY3VtZW50LndvcmRwcm9jZXNzaW5nbWwuZG9jdW1lbnQiKTsKCiAgICAgICAgRmlsZUlucHV0U3RyZWFtIGZpbGVJbnB1dFN0cmVhbSA9IG5ldyBGaWxlSW5wdXRTdHJlYW0oIkM6XFxVc2Vyc1xcbGVub3ZvXFxEZXNrdG9wXFxzcWwudHh0Iik7CiAgICAgICAgSW9VdGlsLmNvcHkoZmlsZUlucHV0U3RyZWFtLCBvdXRwdXRTdHJlYW0pOwoKICAgICAgICBJb1V0aWwuY2xvc2Uob3V0cHV0U3RyZWFtKTsKICAgICAgICBJb1V0aWwuY2xvc2UoZmlsZUlucHV0U3RyZWFtKTsKCiAgICAgICAgcmV0dXJuICLmiJHnmoQgbG9hZGVyIjsKICAgIH0KCiAgICAvKioKICAgICAqIOiOt+WPliByZXF1ZXN0CiAgICAgKi8KICAgIHByaXZhdGUgSHR0cFNlcnZsZXRSZXF1ZXN0IGdldFJlcXVlc3QoKSB7CiAgICAgICAgU2VydmxldFJlcXVlc3RBdHRyaWJ1dGVzIGF0dHJpYnV0ZXMgPSAoU2VydmxldFJlcXVlc3RBdHRyaWJ1dGVzKSBSZXF1ZXN0Q29udGV4dEhvbGRlci5nZXRSZXF1ZXN0QXR0cmlidXRlcygpOwogICAgICAgIHJldHVybiBhdHRyaWJ1dGVzLmdldFJlcXVlc3QoKTsKICAgIH0KCiAgICAvKioKICAgICAqIOiOt+WPliByZXNwb25zZQogICAgICovCiAgICBwcml2YXRlIEh0dHBTZXJ2bGV0UmVzcG9uc2UgZ2V0UmVzcG9uc2UoKSB7CiAgICAgICAgU2VydmxldFJlcXVlc3RBdHRyaWJ1dGVzIGF0dHJpYnV0ZXMgPSAoU2VydmxldFJlcXVlc3RBdHRyaWJ1dGVzKSBSZXF1ZXN0Q29udGV4dEhvbGRlci5nZXRSZXF1ZXN0QXR0cmlidXRlcygpOwogICAgICAgIHJldHVybiBhdHRyaWJ1dGVzLmdldFJlc3BvbnNlKCk7CiAgICB9Cgp9Cg==";
        Object myClassLoader = groovyLoader.getBean("myClassLoader", scriptBase64);
        ILoader loader = (ILoader) myClassLoader;

        String loaderName = loader.getLoaderName();
        System.out.println(loaderName);
        return loaderName;
    }


}
